export const employees = [
  {
    firstName: "Lila",
    lastName: "Lalobil",
    dateBirth: "13/05/1972",
    startDate: "10/05/2016",
    street: "30 rue Stars",
    city: "Guam",
    state: "GU",
    zipCode: 96910,
    department: "Marketing",
  },
  {
    firstName: "Rosie",
    lastName: "Spiner",
    dateBirth: "13/03/1963",
    startDate: "01/01/2010",
    street: "27 Rue Summer",
    city: "Louisiana",
    state: "LA",
    zipCode: 71497,
    department: "Engineering",
  },
  {
    firstName: "Bob",
    lastName: "Driver",
    dateBirth: "09/09/1990",
    startDate: "07/12/2016",
    street: "45 Rue Road",
    city: "Marshall Islands",
    state: "MH",
    zipCode: 96960,
    department: "Sales",
  }
]
